{% set name = "spacy-transformers" %}
{% set module_name = "spacy_transformers" %}
{% set version = "1.2.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 859c2093fad9ff41005bc55c0018d4290bdd62454f76bddbcf318aae85f307b5

build:
  number: 0
  # spacy isn't available on s390x
  skip: True  # [py<36 or s390x]
  # At present, there are no 3.11 compatible Pytorch version for win or ppc
  # There is a bug requiring PyTorch 1.10 on osx-64 which is not available for 3.11
  # As transformers 4.29.2 b0 has the same issue, we apply its skipping logic here  
  skip: True  # [py>310 and (ppc64le or win or (osx and x86_64))]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - cython 0.29.32
    - numpy {{ numpy }}
    - pip
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    # TODO: Working around osx bug importing two openmp variants.
    - pytorch >=1.8.0     # [not (osx and x86_64)]
    - pytorch >1.9,<1.12  # [osx and x86_64]
    - spacy >=3.5.0,<4.0.0
    - spacy-alignments >=0.7.2,<1.0.0
    - srsly >=2.4.0,<3.0.0
    - transformers >=3.4.0,<4.30.0

test:
  requires:
    - pip
    - pytest >=5.2.0
  imports:
    - {{ module_name }}
  commands:
    - pip check
    # tests take too long (hours) on ppc64le and aarch64 
    - python -m pytest --tb=native --pyargs {{ module_name }}  # [not linux and (ppc64le or aarch64)]

about:
  home: https://spacy.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Use pretrained transformers like BERT, XLNet and GPT-2 in spaCy
  description: |
    This package provides spaCy components and architectures to use transformer
    models via Hugging Face's transformers in spaCy. The result is convenient
    access to state-of-the-art transformer architectures, such as BERT, GPT-2,
    XLNet, etc.
  doc_url: https://spacy.io/usage/embeddings-transformers
  dev_url: https://github.com/explosion/spacy-transformers

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
  skip-lints:
    - cython_needs_compiler
